name: 'Build, test and lint'

runs:
  using: 'composite'

  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        hatch env create
