name: CI on push

on:
  push:
    branches-ignore:
      - 'main'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies using Hatch
        uses: ./.github/install-dependencies/

      - name: Run linter using Hatch
        uses: ./.github/run-linter/

      - name: Run tests using Hatch
        uses: ./.github/run-tests/